services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      apinet:
        ipv4_address: 10.0.0.10
    volumes:
      - ./api:/app/api:ro
      - ./internal:/app/internal:ro
      - ./www:/app/www:ro

networks:
  apinet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

